### ISSUE TITLE
Missing Elden Ring Boss in Autosplit Menu

### ISSUE THREAD

**Issue by Freeeshooter** [FrankvdStam/SoulSplitter#36]
There's a missing boss in the list of bosses for Elden Ring when attempting to set up the autosplitter. The Pumpkinhead Duo in Caelid is not on the list. It appears they may have been replaced by 2 Monstrous Dogs on the list instead 
![image](https://github.com/FrankvdStam/SoulSplitter/assets/69083503/e36a5b52-b71b-458b-a5e8-25fe806beaa2)

**Comment by FrankvdStam** [comment]
Thanks for reporting this. Will have time to look into it in +- a week.

**Comment by FrankvdStam** [comment]
The flag value appears twice in the list and corresponds to pumpkin head duo. For some reason it takes the name of the first entry which happens to be monstrous dog, I can fix that.

Problem is now, what is a monstrous dog. I don't see any "monstrous dog" in any boss list or on the map. 

The description suggests it's southwest of caelid highway south, but there is no boss to the west of this grace. Only to the southeast, and its Ekzykes which is already on the list.

I originally got this bosslist + flags from dumped game data, I'm thinking this "Monstrous Dog" might be a boss that was eventually scrapped from the game, which would explain why the flag is a duplicate.

It's been very long since I played ER though, can you maybe confirm/deny if "Monstrous Dog" is an actual boss in the game? maybe I'm overlooking something.

**Comment by Freeeshooter** [comment]
Monstrous Dog is not a boss, it is a normal enemy type but it never appears as a boss. Several of them do appear in the area around the pumpkin head duo boss arena, so maybe that flag name just got missed by the devs when they switched what boss would be there at some point? I can test if killing the pumpkinhead duo with the monstrous dog flag set up for autosplit works to confirm the theory

**Comment by Freeeshooter** [comment]
I just tested and was able to confirm that having the Monstrous Dog flag for autosplitting does in fact work for the pumpkinhead duo

**Comment by FrankvdStam** [comment]
Just gona remove Monstrous Dog then, thanks.

**Comment by FrankvdStam** [comment]
This has been fixed in https://github.com/FrankvdStam/SoulSplitter/pull/38 and merged, you will notice the effects on the next soulsplitter update.
